// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWI7m2_eOHxPx2_gV5MikgCStYdsoGIm8',
    appId: '1:979824494785:web:ba30dbf09373dac6e9ec40',
    messagingSenderId: '979824494785',
    projectId: 'invit-19028',
    authDomain: 'invit-19028.firebaseapp.com',
    storageBucket: 'invit-19028.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD2qXFQ_ye0N7xFKKE3LnuUgHpcqls560',
    appId: '1:979824494785:android:f9c332b188a8abfce9ec40',
    messagingSenderId: '979824494785',
    projectId: 'invit-19028',
    storageBucket: 'invit-19028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHmRq9NKLCElRHhh4Orb3kVbAQa1hn6gY',
    appId: '1:979824494785:ios:b680bd4176272a1de9ec40',
    messagingSenderId: '979824494785',
    projectId: 'invit-19028',
    storageBucket: 'invit-19028.appspot.com',
    iosBundleId: 'com.example.invit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHmRq9NKLCElRHhh4Orb3kVbAQa1hn6gY',
    appId: '1:979824494785:ios:b680bd4176272a1de9ec40',
    messagingSenderId: '979824494785',
    projectId: 'invit-19028',
    storageBucket: 'invit-19028.appspot.com',
    iosBundleId: 'com.example.invit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWI7m2_eOHxPx2_gV5MikgCStYdsoGIm8',
    appId: '1:979824494785:web:a8703abe15528021e9ec40',
    messagingSenderId: '979824494785',
    projectId: 'invit-19028',
    authDomain: 'invit-19028.firebaseapp.com',
    storageBucket: 'invit-19028.appspot.com',
  );

}